In [1]:
import pandas as pd
from fractions import Fraction

## 2.3 Bayes Tables

In [2]:
table = pd.DataFrame(index=['Bowl 1', 'Bowl 2'])
table['prior'] = 1/2, 1/2
table['likelihood'] = 0.75, 0.5
table['unnormalized_posterior'] = table['prior'] * table['likelihood']
table['posterior'] = table['unnormalized_posterior'] / table['unnormalized_posterior'].sum()
print(table)

        prior  likelihood  unnormalized_posterior  posterior
Bowl 1    0.5        0.75                   0.375        0.6
Bowl 2    0.5        0.50                   0.250        0.4

## 2.4 The Dice Problem

In [3]:
table2 = pd.DataFrame(index=[6, 8, 12])
table2['prior'] = Fraction(1, 3)
table2['likelihood'] = Fraction(1, 6), Fraction(1, 8), Fraction(1, 12)

def update(table):
    """Compute the posterior probabilities."""
    table = table.copy()
    table['unnormalized_posterior'] = table['prior'] * table['likelihood']
    prob_data = table['unnormalized_posterior'].sum()
    table['posterior'] = table['unnormalized_posterior'] / prob_data
    return table

update(table2)

   prior likelihood unnormalized_posterior posterior
6    1/3        1/6                   1/18       4/9
8    1/3        1/8                   1/24       1/3
12   1/3       1/12                   1/36       2/9

## 2.5 The Monty Hall Problem

In [4]:
table3 = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table3['prior'] = Fraction(1, 3)
table3['likelihood'] = Fraction(1, 2), 1, 0
update(table3)

       prior likelihood unnormalized_posterior posterior
Door 1   1/3        1/2                    1/6       1/3
Door 2   1/3          1                    1/3       2/3
Door 3   1/3          0                      0         0

## 2.7 Exercises
### 2.7.1 Exercise 1

In [5]:
table = pd.DataFrame(index=['Real', 'Fake'])
table['prior'] = Fraction(1, 2)
table['likelihood'] = Fraction(1, 2), 1
update(table)

     prior likelihood unnormalized_posterior posterior
Real   1/2        1/2                    1/4       1/3
Fake   1/2          1                    1/2       2/3

### 2.7.2 Exercise 2

In [6]:
table = pd.DataFrame(index=['BB', 'BG', 'GG'])
table['prior'] = Fraction(1, 4), Fraction(1, 2), Fraction(1, 4)
table['likelihood'] = 0, 1, 1
update(table)

   prior  likelihood unnormalized_posterior posterior
BB   1/4           0                      0         0
BG   1/2           1                    1/2       2/3
GG   1/4           1                    1/4       1/3

### 2.7.3 Exercise 3

In [7]:
table = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table['prior'] = Fraction(1, 3), Fraction(1, 3), Fraction(1, 3)
table['likelihood'] = 1, 0, 1
update(table)

       prior  likelihood unnormalized_posterior posterior
Door 1   1/3           1                    1/3       1/2
Door 2   1/3           0                      0         0
Door 3   1/3           1                    1/3       1/2

In [8]:
table = pd.DataFrame(index=['Door 1', 'Door 2', 'Door 3'])
table['prior'] = Fraction(1, 3), Fraction(1, 3), Fraction(1, 3)
table['likelihood'] = 0, 1, 0
update(table)

       prior  likelihood unnormalized_posterior posterior
Door 1   1/3           0                      0         0
Door 2   1/3           1                    1/3         1
Door 3   1/3           0                      0         0

### 2.7.4 Exercise 4

In [11]:
table = pd.DataFrame(index=['1994 -> Yellow, 1996 -> Green', '1996 -> Yellow, 1994 -> Green'])
table['prior'] = 0.5, 0.5
table['likelihood'] = 0.2 * 0.2, 0.14 * 0.1
update(table)

,prior,likelihood,unnormalized_posterior,posterior
"1994 -> Yellow, 1996 -> Green",0.5,0.040,0.020,0.740741
"1996 -> Yellow, 1994 -> Green",0.5,0.014,0.007,0.259259